stages:
  - checkstyle
  - deploy

checkstyle:
  stage: checkstyle
  image: maven:3.8.3-openjdk-17
  script:
    - mvn -B clean checkstyle:check -s $MAVEN_SETTINGS_XML
  tags:
    - ci-docker
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - when: never

deploy:
  stage: deploy
  image: maven:3.8.3-openjdk-17
  tags:
    - ci-docker
  script:
    - if [[ $CI_COMMIT_BRANCH == release* ]]; then export version="${CI_COMMIT_BRANCH##*/}"; else export version="$CI_COMMIT_SHA-SNAPSHOT" ;fi
    - echo "version is $version"
    - mvn versions:set -DnewVersion=$version
    - mvn clean deploy -Dmaven.test.skip -P ci -s ci_settings.xml
  rules:
    - if: '$CI_COMMIT_BRANCH =~ "/^release/"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: manual
